apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: default
data:
  Corefile: |
    home-lab.com:53 {
        log
        errors
        health
        file /etc/coredns/zones/home-lab
    }

    .:53 {
        hosts /etc/coredns/blocklist/adblock.hosts {
            reload 30s
            fallthrough
        }
        template IN ANY instagram.com {
            rcode NXDOMAIN
        }
        template IN ANY welt.de {
            rcode NXDOMAIN
        }
        template IN ANY mopo.de {
            rcode NXDOMAIN
        }
        template IN ANY bild.de {
            rcode NXDOMAIN
        }
        log
        errors
        health
        prometheus :9153
        cache 30
        forward . 192.168.178.1
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-zone
  namespace: default
data:
  home-lab: |
    $ORIGIN home-lab.com.
    @       86400 IN SOA ns.home-lab.com. admin.home-lab.com. (
                2024020101 ; Serial
                3600       ; Refresh
                1800       ; Retry
                604800     ; Expire
                86400 )    ; Negative Cache TTL

    ; Name servers
    @       IN NS   ns.home-lab.com.

    ; DNS server hostname
    ns      IN A    192.168.178.29

    ; Hostnames
    grafana      IN A    192.168.178.29
    influxdb     IN A    192.168.178.29
    postgres     IN A    192.168.178.29
    prometheus   IN A    192.168.178.29
    frontend     IN A    192.168.178.29
    backend      IN A    192.168.178.29

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homedns
  namespace: default
  labels:
    app: homedns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homedns
  template:
    metadata:
      labels:
        app: homedns
    spec:
      hostNetwork: true
      dnsPolicy: Default

      initContainers:
        - name: fetch-blocklist
          image: localhost:5000/curlimages/curl:8.17.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              mkdir -p /etc/coredns/blocklist
              
              curl -fsSL https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts \
                | awk 'NF && $1 ~ /^(0\.0\.0\.0|127\.0\.0\.1)$/ && $2 ~ /^[A-Za-z0-9.-]+$/ {print "0.0.0.0 " $2}' \
                | sed 's/\r$//' \
                > /etc/coredns/blocklist/adblock.hosts

              tail -10 /etc/coredns/blocklist/adblock.hosts
          volumeMounts:
            - name: blocklist-volume
              mountPath: /etc/coredns/blocklist

      containers:
        - name: debug
          image: busybox:1.36
          command: ["sleep", "3600"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
            - name: blocklist-volume
              mountPath: /etc/coredns/blocklist
        - name: coredns
          image: coredns/coredns:1.13.2
          args: [ "-conf", "/etc/coredns/Corefile" ]
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
            - name: config-zone
              mountPath: /etc/coredns/zones
            - name: blocklist-volume
              mountPath: /etc/coredns/blocklist
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: coredns-config
            items:
              - key: Corefile
                path: Corefile
        - name: config-zone
          configMap:
            name: coredns-zone
        - name: blocklist-volume
          emptyDir: {}
