apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mount-blocklist
spec:
  storageClassName: local-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  volumeName: local-mount-blocklist