apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mount-pvc
spec:
  storageClassName: local-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: local-mount-pvc