apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kube-test
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.kube.test.com`)
      kind: Rule
      services:
        - kind: Service
          name: kube-prometheus-stack-prometheus
          port: 9090
    - match: Host(`grafana.kube.test.com`)
      kind: Rule
      services:
        - kind: Service
          name: grafana-service
          port: 3000
    - match: Host(`influxdb.kube.test.com`)
      kind: Rule
      services:
        - kind: Service
          name: influxdb-service
          port: 8086
    - match: Host(`postgres.kube.test.com`)
      kind: Rule
      services:
        - kind: Service
          name: postgres-service
          port: 5432
    - match: Host(`app.kube.test.com`)
      kind: Rule
      services:
        - kind: Service
          name: applications-service
          port: 9055
