apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-routes
  namespace: default
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postgres-service
          port: 5432
