apiVersion: v1
kind: Secret
metadata:
  name: influxdb-token
  namespace: default
  labels:
    app: grafana
    component: datasource
type: Opaque
data:
  # Token: rmz5aaaKYSpgvXSO3C1UFZmXjvtpwI81b7hcMaMJJqOTjvgI82iNAbSsF7fpGIy2fduNDKACQ759cyaiECrulg==
  token: cm16NWFhYUtZU3BndlhTTzNDMVVGWm1YanZ0cHdJODFiN2hjTW1NSmpxT1RqdmdJODJpTmFiU2ZGNnBHSVkyZmR1TkRLQUNRNzU5Y3lhaUVDcnVsZz09